
automation:
  - alias: Turn lights red when hot
    trigger:
      - platform: numeric_state
        entity_id: sensor.living_room_temp
        above: 30
    action:
      - service: hue.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Alert Red"
